#!/usr/bin/env python3
"""Extract numeric arrays from CCBlade.jl/test/runtests.jl into test_arrays.h
so the C test suite uses byte-identical data. Scales like 1e3*[...] or
pi/180*[...] are emitted as separate constants applied at compare time."""
import re
import sys

SRC = "/home/cosku/Documents/bemt/CCBlade.jl/test/runtests.jl"
OUT = "/home/cosku/Documents/bemt/ccbladecc/tests/test_arrays.h"

text = open(SRC).read()

# (C name, julia var, occurrence index (0-based), scale expr or None)
WANT = [
    ("INGRAM_R", "r", 0, None),
    ("INGRAM_GAMMA", "gamma", 0, None),
    ("INGRAM_CHORD", "chord", 0, None),
    ("TSIM", "tsim", 0, "1e3"),
    ("QSIM", "qsim", 0, "1e2"),
    ("NREL_R", "r", 1, None),
    ("NREL_CHORD", "chord", 1, None),
    ("NREL_THETA", "theta", 0, "CC_PI/180"),
    ("AF_IDX", "af_idx", 0, None),
    ("NPNORM", "Npnorm", 0, None),
    ("TPNORM", "Tpnorm", 0, None),
    ("CPVEC_TEST", "cpvec_test", 0, None),
    ("CTVEC_TEST", "ctvec_test", 0, None),
    ("PROP_R", "r", 2, "0.0254"),
    ("PROP_CHORD", "chord", 2, "0.0254"),
    ("PROP_THETA", "theta", 1, "CC_PI/180"),
    ("NPTEST", "Nptest", 0, None),
    ("TPTEST", "Tptest", 0, None),
    ("UNORMTEST", "unormtest", 0, None),
    ("VNORMTEST", "vnormtest", 0, None),
    ("CTTEST", "CTtest", 0, None),
    ("CPTEST", "CPtest", 0, None),
    ("ETATEST", "etatest", 0, None),
    ("CTCOMP", "CTcomp", 0, None),
    ("CQCOMP", "CQcomp", 0, None),
    ("DS_ALPHAVEC", "alphavec", 0, "CC_PI/180"),
    ("DS_CL2D", "cl2d", 0, None),
    ("DS_CLEXCEL1", "clexcel", 0, None),
    ("DS_CLEXCEL2", "clexcel", 1, None),
    ("DS2_ALPHAVEC", "alphavec", 1, "CC_PI/180"),
    ("DS2_CL2D", "cl2d", 1, None),
    ("DS2_CLEXCEL1", "clexcel", 2, None),
    ("DS2_CLEXCEL2", "clexcel", 3, None),
    ("DS2_CLEXCEL3", "clexcel", 4, None),
]

# find all assignments: var = [ ... ] or var = scale*[ ... ] (non-nested brackets)
pattern = re.compile(
    r"(?m)^([A-Za-z_]\w*)\s*=\s*(?:([\w\./\*]+)\s*\*\s*)?\[([^\[\]]*)\]"
)

occurrences = {}
for m in pattern.finditer(text):
    var, scale, body = m.group(1), m.group(2), m.group(3)
    occurrences.setdefault(var, []).append((scale, body))

out = ["// Auto-generated by extract_arrays.py from runtests.jl.",
       "// Do not edit by hand.", ""]
for cname, var, occ, scale_override in WANT:
    entries = occurrences.get(var, [])
    if occ >= len(entries):
        sys.exit(f"missing {var} occurrence {occ}")
    scale, body = entries[occ]
    nums = [x for x in re.split(r"[,\s]+", body.strip()) if x]
    vals = []
    for x in nums:
        if not re.fullmatch(r"[-+0-9.eE]+", x):
            sys.exit(f"non-numeric token {x!r} in {var}")
        vals.append(float(x))
    n = len(vals)
    out.append(f"#define {cname}_N {n}")
    out.append(f"static const double {cname}[{cname}_N] = {{")
    for i in range(0, n, 4):
        chunk = ", ".join(f"{v:.17e}" for v in vals[i:i+4])
        out.append("    " + chunk + ("," if i + 4 < n else ""))
    out.append("};")
    out.append("")

open(OUT, "w").write("\n".join(out))
print(f"wrote {OUT}")
