# Extract numeric arrays from the vendored CCBlade.jl test suite
# (vendor/CCBlade.jl/test/runtests.jl) into test_arrays.h so the C test
# suite uses byte-identical data. Scales like 1e3*[...] or pi/180*[...]
# are emitted as separate constants applied at compare time.
# Uses the vendored CCBlade.jl submodule (git submodule update --init).
# Run from tests/:  julia extract_arrays.jl

using Printf

src = joinpath(@__DIR__, "..", "vendor", "CCBlade.jl", "test", "runtests.jl")
out_path = joinpath(@__DIR__, "test_arrays.h")

isfile(src) || error("$src not found; run: git submodule update --init")

text = read(src, String)

# (C name, julia var, occurrence index (0-based), scale expr or nothing)
WANT = [
    ("INGRAM_R", "r", 0, nothing),
    ("INGRAM_GAMMA", "gamma", 0, nothing),
    ("INGRAM_CHORD", "chord", 0, nothing),
    ("TSIM", "tsim", 0, "1e3"),
    ("QSIM", "qsim", 0, "1e2"),
    ("NREL_R", "r", 1, nothing),
    ("NREL_CHORD", "chord", 1, nothing),
    ("NREL_THETA", "theta", 0, "CC_PI/180"),
    ("AF_IDX", "af_idx", 0, nothing),
    ("NPNORM", "Npnorm", 0, nothing),
    ("TPNORM", "Tpnorm", 0, nothing),
    ("CPVEC_TEST", "cpvec_test", 0, nothing),
    ("CTVEC_TEST", "ctvec_test", 0, nothing),
    ("PROP_R", "r", 2, "0.0254"),
    ("PROP_CHORD", "chord", 2, "0.0254"),
    ("PROP_THETA", "theta", 1, "CC_PI/180"),
    ("NPTEST", "Nptest", 0, nothing),
    ("TPTEST", "Tptest", 0, nothing),
    ("UNORMTEST", "unormtest", 0, nothing),
    ("VNORMTEST", "vnormtest", 0, nothing),
    ("CTTEST", "CTtest", 0, nothing),
    ("CPTEST", "CPtest", 0, nothing),
    ("ETATEST", "etatest", 0, nothing),
    ("CTCOMP", "CTcomp", 0, nothing),
    ("CQCOMP", "CQcomp", 0, nothing),
    ("DS_ALPHAVEC", "alphavec", 0, "CC_PI/180"),
    ("DS_CL2D", "cl2d", 0, nothing),
    ("DS_CLEXCEL1", "clexcel", 0, nothing),
    ("DS_CLEXCEL2", "clexcel", 1, nothing),
    ("DS2_ALPHAVEC", "alphavec", 1, "CC_PI/180"),
    ("DS2_CL2D", "cl2d", 1, nothing),
    ("DS2_CLEXCEL1", "clexcel", 2, nothing),
    ("DS2_CLEXCEL2", "clexcel", 3, nothing),
    ("DS2_CLEXCEL3", "clexcel", 4, nothing),
]

# find all assignments: var = [ ... ] or var = scale*[ ... ] (non-nested brackets)
pattern = r"(?m)^([A-Za-z_]\w*)\s*=\s*(?:([\w\./\*]+)\s*\*\s*)?\[([^\[\]]*)\]"

occurrences = Dict{String, Vector{Tuple{Union{Nothing, SubString}, SubString}}}()
for m in eachmatch(pattern, text)
    var, scale, body = m.captures
    push!(get!(occurrences, var, []), (scale, body))
end

out = ["// Auto-generated by extract_arrays.jl from runtests.jl.",
       "// Do not edit by hand.", ""]
for (cname, var, occ, _scale) in WANT
    entries = get(occurrences, var, [])
    occ < length(entries) || error("missing $var occurrence $occ")
    _, body = entries[occ + 1]
    nums = filter(!isempty, split(strip(body), r"[,\s]+"))
    vals = map(nums) do x
        occursin(r"^[-+0-9.eE]+$", x) || error("non-numeric token $(repr(x)) in $var")
        parse(Float64, x)
    end
    n = length(vals)
    push!(out, "#define $(cname)_N $n")
    push!(out, "static const double $cname[$(cname)_N] = {")
    for i in 1:4:n
        chunk = join([@sprintf("%.17e", v) for v in vals[i:min(i + 3, n)]], ", ")
        push!(out, "    " * chunk * (i + 4 <= n ? "," : ""))
    end
    push!(out, "};")
    push!(out, "")
end

write(out_path, join(out, "\n"))
println("wrote $out_path")
