# Generates reference_data.h for the C test suite.
# Covers functions not exercised by the Julia test suite:
# viterna, AlphaReAF, AlphaMachAF, AlphaReMachAF (evaluation), and akima spot checks.
# Run from the CCBlade.jl project:  julia --project=../CCBlade.jl gen_reference.jl

using CCBlade
using Printf

outdir = @__DIR__
fh = open(joinpath(outdir, "reference_data.h"), "w")

println(fh, "// Auto-generated by gen_reference.jl from the Julia CCBlade implementation.")
println(fh, "// Do not edit by hand.")
println(fh)

printvec(name, v) = begin
    println(fh, "#define $(name)_N $(length(v))")
    println(fh, "static const double $name[$(name)_N] = {")
    for i in 1:length(v)
        @printf(fh, "%.17e%s", v[i], i < length(v) ? ", " : "")
        if i % 4 == 0 && i < length(v)
            println(fh)
        end
    end
    println(fh, "};")
end


# ---------- viterna ----------
# Use a subset of the NACA64 polar (attached + stall region) and extrapolate to +/-180.
alpha64, cl64, cd64 = let
    _, _, _, a, cl, cd = CCBlade.parsefile(joinpath(outdir, "airfoils/NACA64_A17.dat"), false)
    idx = findall((a .>= -20.0*pi/180) .& (a .<= 30.0*pi/180))
    a[idx], cl[idx], cd[idx]
end
cr75 = 0.25
nalpha_v = 50
av, clv, cdv = viterna(alpha64, cl64, cd64, cr75, nalpha_v)

println(fh, "")
printvec("VITERNA_ALPHA", av)
printvec("VITERNA_CL", clv)
printvec("VITERNA_CD", cdv)
println(fh)

# ---------- akima spot check ----------
x = collect(range(0.0, 10.0, length=11))
y = sin.(x) .* exp.(-0.1 .* x)
xq = [0.3, 1.7, 2.5, 3.33, 5.5, 7.77, 9.9, -0.5, 10.6]  # includes extrapolation
yq = FLOWMath_akima_check = CCBlade.FLOWMath.akima(x, y, xq)
println(fh, "#define AKIMA_NQ $(length(xq))")
printvec("AKIMA_X", x)
printvec("AKIMA_Y", y)
printvec("AKIMA_XQ", collect(xq))
printvec("AKIMA_YQ", yq)
println(fh)

# ---------- AlphaReAF ----------
alpha = collect(range(-pi, pi, length=25))
Re = [5e4, 1e5, 2e5, 5e5]
clm = [sin(2*a)*(1 + 0.1*log10(r/1e5)) + 0.05*a for a in alpha, r in Re]
cdm = [0.02 + 0.03*sin(a)^2 + 0.01*(r/1e5)^-0.2*cos(a)^2 for a in alpha, r in Re]
afre = AlphaReAF(alpha, Re, clm, cdm)

aq = [-2.9, -0.7, 0.13, 0.44, 1.2, 2.6]
rq = [6e4, 8.7e4, 1.5e5, 3.3e5, 4.9e5, 1.1e5]
clq = [afeval(afre, a, r, 0.0)[1] for (a, r) in zip(aq, rq)]
cdq = [afeval(afre, a, r, 0.0)[2] for (a, r) in zip(aq, rq)]

println(fh, "#define AFRE_NQ $(length(aq))")
printvec("AFRE_ALPHA", alpha)
printvec("AFRE_RE", Re)
printvec("AFRE_CLM", vec(clm))   # column-major like Julia
printvec("AFRE_CDM", vec(cdm))
printvec("AFRE_AQ", aq)
printvec("AFRE_RQ", rq)
printvec("AFRE_CLQ", clq)
printvec("AFRE_CDQ", cdq)
println(fh)

# ---------- AlphaMachAF ----------
Mach = [0.0, 0.3, 0.6, 0.8]
clm2 = [sin(2*a)/sqrt(1 - min(m^2, 0.81)) for a in alpha, m in Mach]
cdm2 = [0.02 + 0.04*sin(a)^2*(1 + m) for a in alpha, m in Mach]
afmach = AlphaMachAF(alpha, Mach, clm2, cdm2)

mq = [0.1, 0.45, 0.7, 0.77, 0.02, 0.55]
clq2 = [afeval(afmach, a, 0.0, m)[1] for (a, m) in zip(aq, mq)]
cdq2 = [afeval(afmach, a, 0.0, m)[2] for (a, m) in zip(aq, mq)]

println(fh, "#define AFMACH_NQ $(length(aq))")
printvec("AFMACH_MACH", Mach)
printvec("AFMACH_CLM", vec(clm2))
printvec("AFMACH_CDM", vec(cdm2))
printvec("AFMACH_MQ", mq)
printvec("AFMACH_CLQ", clq2)
printvec("AFMACH_CDQ", cdq2)
println(fh)

# ---------- AlphaReMachAF ----------
Re2 = [8e4, 1.6e5]
Mach2 = [0.0, 0.4, 0.7]
clm3 = [sin(2*a)*(1 + 0.1*log10(r/1e5))/sqrt(1 - min(m^2, 0.81)) for a in alpha, r in Re2, m in Mach2]
cdm3 = [0.02 + 0.03*sin(a)^2 + 0.005*m for a in alpha, r in Re2, m in Mach2]
afremach = AlphaReMachAF(alpha, Re2, Mach2, clm3, cdm3)

rq3 = [9e4, 1.2e5, 1.55e5, 8.4e4, 1.1e5, 1.6e5]
mq3 = [0.1, 0.3, 0.65, 0.55, 0.2, 0.4]
clq3 = [afeval(afremach, a, r, m)[1] for (a, r, m) in zip(aq, rq3, mq3)]
cdq3 = [afeval(afremach, a, r, m)[2] for (a, r, m) in zip(aq, rq3, mq3)]

println(fh, "#define AFREMACH_NQ $(length(aq))")
printvec("AFREMACH_RE", Re2)
printvec("AFREMACH_MACH", Mach2)
printvec("AFREMACH_CLM", vec(clm3))
printvec("AFREMACH_CDM", vec(cdm3))
printvec("AFREMACH_RQ", rq3)
printvec("AFREMACH_MQ", mq3)
printvec("AFREMACH_CLQ", clq3)
printvec("AFREMACH_CDQ", cdq3)

close(fh)
println("reference_data.h written")
