/*
 * runtests.c — C port of the Julia test suite (test/runtests.jl), covering
 * the portable testsets: "normal operation", "qualitative check",
 * "correction methods".  Julia-specific sets (derivatives via ForwardDiff,
 * type stability, broadcasting, esoteric arrays) are not applicable.
 *
 * An additional "reference data" set cross-checks viterna, the Akima spline,
 * and the Re/Mach-dependent airfoil evaluators against values generated by
 * the Julia implementation (reference_data.h, from gen_reference.jl).
 */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ccblade.h"
#include "reference_data.h"
#include "test_arrays.h"

static int n_pass = 0, n_fail = 0;

static void check_approx(double actual, double expected, double atol,
                         const char* expr, int line) {
  if (fabs(actual - expected) <= atol) {
    n_pass++;
  } else {
    n_fail++;
    printf("FAIL (line %d): %s = %.17g, expected %.17g (atol %g)\n", line, expr,
           actual, expected, atol);
  }
}

#define CHECK(actual, expected, atol) \
  check_approx((actual), (expected), (atol), #actual, __LINE__)

/* ------------ airfoil callbacks (ports of the Julia test closures) ------- */

static void affunc_ingram(double alpha, double Re, double M, void* ud,
                          double* cl, double* cd) {
  (void)Re;
  (void)M;
  (void)ud;
  *cl = 0.084 * alpha * 180.0 / CC_PI;
  *cd = 0.0;
}

static void affunc2(double alpha, double Re, double M, void* ud, double* cl,
                    double* cd) {
  (void)Re;
  (void)M;
  (void)ud;
  *cl = 6.2 * alpha;
  *cd = 0.008 - 0.003 * (*cl) + 0.01 * (*cl) * (*cl);
}

static void affunc3(double alpha, double Re, double M, void* ud, double* cl,
                    double* cd) {
  double alpha0 = *(double*)ud;
  (void)Re;
  (void)M;
  *cl = 6.2 * (alpha - alpha0);
  *cd = 0.008 - 0.003 * (*cl) + 0.01 * (*cl) * (*cl);
}

/* naca0012 polar from file with cd offset by +0.014 (hover test) */
// cppcheck-suppress constParameterCallback
static void affunc_hover(double alpha, double Re, double M, void* ud,
                         double* cl, double* cd) {
  const CCAirfoil* base = (const CCAirfoil*)ud;
  cc_afeval(base, alpha, Re, M, cl, cd);
  *cd += 0.014;
}

static double linspace(double a, double b, int n, int i) {
  return a + (b - a) * i / (n - 1);
}

/* ============================ normal operation ========================== */

static void test_normal_operation(void) {
  /* --- Ingram wind turbine verification --- */
  double Rhub = 0.01;
  double Rtip = 5.0;
  double Rtip_eff = 5.0 * 100;
  int B = 3;

  CCRotor rotor = cc_rotor(Rhub, Rtip_eff, B);
  rotor.turbine = 1;

  int nr = INGRAM_R_N;
  CCSection* sections = malloc(sizeof(CCSection) * nr);
  if (!sections) {
    n_fail++;
    printf("FAIL: malloc sections\n");
    return;
  }
  CCAirfoil* af = cc_af_function(affunc_ingram, NULL);
  for (int i = 0; i < nr; i++) {
    sections[i].r = INGRAM_R[i];
    sections[i].chord = INGRAM_CHORD[i];
    sections[i].theta = (90.0 - INGRAM_GAMMA[i]) * CC_PI / 180.0;
    sections[i].af = af;
  }

  double Vinf = 7.0, tsr = 8.0;
  double Omega = tsr * Vinf / Rtip;
  double rho = 1.0;

  CCOutputs* out = malloc(sizeof(CCOutputs) * nr);
  if (!out) {
    free(sections);
    cc_af_free(af);
    n_fail++;
    printf("FAIL: malloc out\n");
    return;
  }
  for (int i = 0; i < nr; i++) {
    CCOperatingPoint op = cc_simple_op(Vinf, Omega, sections[i].r, rho);
    out[i] = cc_solve(&rotor, &sections[i], &op);
  }

  double beta[INGRAM_R_N];
  for (int i = 0; i < nr; i++) beta[i] = 90.0 - out[i].phi * 180.0 / CC_PI;

  static const double a_exp[5] = {0.2443, 0.2497, 0.2533, 0.2556, 0.25725};
  static const double ap_exp[5] = {0.0676, 0.0180, 0.0081, 0.0046, 0.0030};
  static const double beta_exp[5] = {66.1354, 77.0298, 81.2283, 83.3961,
                                     84.7113};
  for (int i = 0; i < 5; i++) {
    CHECK(out[i + 1].a, a_exp[i], 1e-4);
    CHECK(out[i + 1].ap, ap_exp[i], 1e-4);
    CHECK(beta[i + 1], beta_exp[i], 1e-3);
  }
  free(out);
  free(sections);
  cc_af_free(af);

  /* --- propeller verification (aerodynamics4students spreadsheet) --- */
  {
    double D = 1.6;
    double R = D / 2.0;
    int B2 = 2;
    CCRotor rotor_no_F = cc_rotor(1e-6, 100.0, B2);
    CCRotor rotor2 = cc_rotor(0.0, R, B2);

    int nsec = 11;
    CCSection sec2[11];
    double r[11];
    CCAirfoil* af2 = cc_af_function(affunc2, NULL);
    for (int i = 0; i < nsec; i++) {
      r[i] = linspace(R / 10.0, R, nsec, i);
      sec2[i].r = r[i];
      sec2[i].chord = 0.10;
      sec2[i].theta = atan(1.0 / (2.0 * CC_PI * r[i]));
      sec2[i].af = af2;
    }

    double RPM = 2100.0;
    double rho2 = 1.225;
    double dr = r[1] - r[0];

    for (int i = 1; i <= 60; i++) {
      double V = (double)i;
      double Om = RPM * CC_PI / 30.0;
      double T = 0.0, Q = 0.0;
      for (int j = 0; j < nsec; j++) {
        CCOperatingPoint op = cc_simple_op(V, Om, r[j], rho2);
        CCOutputs o = cc_solve(&rotor_no_F, &sec2[j], &op);
        T += o.Np * dr * B2;
        Q += r[j] * o.Tp * dr * B2;
      }
      CHECK(T, TSIM[i - 1] * 1e3, 1e-2);
      CHECK(Q, QSIM[i - 1] * 1e2, 2e-3);
    }

    /* nondim at Vinf = 20 */
    double V = 20.0;
    double Om = RPM * CC_PI / 30.0;
    double T = 0.0, Q = 0.0;
    for (int j = 0; j < nsec; j++) {
      CCOperatingPoint op = cc_simple_op(V, Om, r[j], rho2);
      CCOutputs o = cc_solve(&rotor_no_F, &sec2[j], &op);
      T += o.Np * dr * B2;
      Q += r[j] * o.Tp * dr * B2;
    }
    double nd[3];
    cc_nondim(T, Q, V, Om, rho2, &rotor2, "propeller", nd);
    CHECK(nd[1], 0.056110238632657, 1e-7);
    CHECK(nd[2], 0.004337202960642, 1e-8);
    CHECK(nd[0], 0.735350632777002, 1e-6);

    /* --- cambered airfoil, exact regression values --- */
    double alpha0 = -3.0 * CC_PI / 180.0;
    CCAirfoil* af3 = cc_af_function(affunc3, &alpha0);
    CCSection sec3[11];
    for (int i = 0; i < nsec; i++) {
      sec3[i] = sec2[i];
      sec3[i].af = af3;
    }

    V = 5.0;
    CCOutputs out3[11];
    T = 0.0;
    Q = 0.0;
    for (int j = 0; j < nsec; j++) {
      CCOperatingPoint op = cc_simple_op(V, Om, r[j], rho2);
      out3[j] = cc_solve(&rotor_no_F, &sec3[j], &op);
      T += out3[j].Np * dr * B2;
      Q += r[j] * out3[j].Tp * dr * B2;
    }

    CHECK(T, 1223.0506862888788, 1e-8);
    CHECK(Q, 113.79919472569034, 1e-8);
    CHECK(out3[3].Np, 427.3902632382494, 1e-8);
    CHECK(out3[3].Tp, 122.38414345762305, 1e-8);
    CHECK(out3[3].a, 2.2845512476210943, 1e-8);
    CHECK(out3[3].ap, 0.05024950801920044, 1e-8);
    CHECK(out3[3].u, 11.422756238105471, 1e-8);
    CHECK(out3[3].v, 3.2709314141649575, 1e-8);
    CHECK(out3[3].phi, 0.2596455971546484, 1e-8);
    CHECK(out3[3].alpha, 0.23369406105568025, 1e-8);
    CHECK(out3[3].W, 63.96697566502531, 1e-8);
    CHECK(out3[3].cl, 1.773534419416163, 1e-8);
    CHECK(out3[3].cd, 0.03413364011028978, 1e-8);
    CHECK(out3[3].cn, 1.7053239640124302, 1e-8);
    CHECK(out3[3].ct, 0.48832327407767123, 1e-8);
    CHECK(out3[3].F, 1.0, 1e-8);
    CHECK(out3[3].G, 1.0, 1e-8);

    /* twisted variant */
    for (int i = 0; i < nsec; i++)
      sec3[i].theta = atan(1.0 / (2.0 * CC_PI * r[i])) - 3.0 * CC_PI / 180.0;
    T = 0.0;
    Q = 0.0;
    for (int j = 0; j < nsec; j++) {
      CCOperatingPoint op = cc_simple_op(V, Om, r[j], rho2);
      CCOutputs o = cc_solve(&rotor_no_F, &sec3[j], &op);
      T += o.Np * dr * B2;
      Q += r[j] * o.Tp * dr * B2;
    }
    CHECK(T, 1e3 * 0.962407923825140, 1e-3);
    CHECK(Q, 1e2 * 0.813015017103876, 1e-4);

    cc_af_free(af2);
    cc_af_free(af3);
  }
}

/* ============================ qualitative check ========================= */

static void test_qualitative(void) {
  /* --- NREL 5MW turbine distributed loads --- */
  double Rhub = 1.5, Rtip = 63.0;
  int B = 3;
  double precone = 2.5 * CC_PI / 180.0;

  CCRotor rotor = cc_rotor(Rhub, Rtip, B);
  rotor.precone = precone;
  rotor.turbine = 1;

  static const char* files[8] = {
      "airfoils/Cylinder1.dat", "airfoils/Cylinder2.dat",
      "airfoils/DU40_A17.dat",  "airfoils/DU35_A17.dat",
      "airfoils/DU30_A17.dat",  "airfoils/DU25_A17.dat",
      "airfoils/DU21_A17.dat",  "airfoils/NACA64_A17.dat"};
  CCAirfoil* aftypes[8];
  for (int i = 0; i < 8; i++) {
    aftypes[i] = cc_af_alpha_file(files[i], 0);
    if (!aftypes[i]) {
      fprintf(stderr, "failed to load %s\n", files[i]);
      n_fail++;
      return;
    }
  }

  int nr = NREL_R_N;
  CCSection sections[17];
  for (int i = 0; i < nr; i++) {
    sections[i].r = NREL_R[i];
    sections[i].chord = NREL_CHORD[i];
    sections[i].theta = NREL_THETA[i] * CC_PI / 180.0;
    sections[i].af = aftypes[(int)AF_IDX[i] - 1];
  }

  double yaw = 0.0, tilt = 5.0 * CC_PI / 180.0;
  double hubHt = 90.0, shearExp = 0.2;
  double Vinf = 10.0, tsr = 7.55;
  double rotorR = Rtip * cos(precone);
  double Omega = Vinf * tsr / rotorR;
  double azimuth = 0.0;
  double rho = 1.225;
  double pitch = 0.0;

  for (int i = 0; i < nr; i++) {
    CCOperatingPoint op =
        cc_windturbine_op(Vinf, Omega, pitch, sections[i].r, precone, yaw, tilt,
                          azimuth, hubHt, shearExp, rho, 1.0, 1.0);
    CCOutputs o = cc_solve(&rotor, &sections[i], &op);
    CHECK(o.Np / 1e3, NPNORM[i], 1e-3);
    CHECK(o.Tp / 1e3, TPNORM[i], 1e-3);
  }

  /* --- CP/CT vs tip speed ratio, azimuthally averaged --- */
  int ntsr = 20;
  static const double azangles[4] = {0.0, CC_PI / 2, CC_PI, 3.0 * CC_PI / 2};
  CCOutputs* outs = malloc(sizeof(CCOutputs) * nr * 4);
  if (!outs) {
    for (int i = 0; i < 8; i++) cc_af_free(aftypes[i]);
    n_fail++;
    printf("FAIL: malloc outs\n");
    return;
  }
  for (int i = 0; i < ntsr; i++) {
    double Om = Vinf * linspace(2.0, 15.0, ntsr, i) / rotorR;
    for (int ir = 0; ir < nr; ir++) {
      for (int j = 0; j < 4; j++) {
        CCOperatingPoint op = cc_windturbine_op(Vinf, Om, pitch, sections[ir].r,
                                                precone, yaw, tilt, azangles[j],
                                                hubHt, shearExp, rho, 1.0, 1.0);
        outs[ir * 4 + j] = cc_solve(&rotor, &sections[ir], &op);
      }
    }
    double T, Q;
    cc_thrusttorque_az(&rotor, sections, outs, nr, 4, &T, &Q);
    double nd[3];
    cc_nondim(T, Q, Vinf, Om, rho, &rotor, "windturbine", nd);
    CHECK(nd[0], CPVEC_TEST[i], 1e-3);
    CHECK(nd[1], CTVEC_TEST[i], 1e-3);
  }
  free(outs);
  for (int i = 0; i < 8; i++) cc_af_free(aftypes[i]);

  /* --- propeller with NACA64 airfoil --- */
  {
    CCRotor rotor2 = cc_rotor(0.0254 * 0.5, 0.0254 * 3.0, 2);
    int nr2 = PROP_R_N;
    CCSection sections2[31];
    for (int i = 0; i < nr2; i++) {
      sections2[i].r = PROP_R[i] * 0.0254;
      sections2[i].chord = PROP_CHORD[i] * 0.0254;
      sections2[i].theta = PROP_THETA[i] * CC_PI / 180.0;
    }
    CCAirfoil* af = cc_af_alpha_file("airfoils/NACA64_A17.dat", 0);
    if (!af) {
      fprintf(stderr, "failed to load NACA64\n");
      n_fail++;
      return;
    }
    for (int i = 0; i < nr2; i++) sections2[i].af = af;

    double rho2 = 1.225;
    double Vinf2 = 10.0;
    double Omega2 = 8000.0 * CC_PI / 30.0;

    for (int i = 0; i < nr2; i++) {
      CCOperatingPoint op = cc_simple_op(Vinf2, Omega2, sections2[i].r, rho2);
      CCOutputs o = cc_solve(&rotor2, &sections2[i], &op);
      CHECK(o.Np, NPTEST[i], 1e-3);
      CHECK(o.Tp, TPTEST[i], 1e-3);
      CHECK(o.u / Vinf2, UNORMTEST[i], 1e-3);
      CHECK(o.v / Vinf2, VNORMTEST[i], 1e-3);
    }

    /* CT/CP/efficiency vs advance ratio */
    int nJ = 20;
    double n = Omega2 / (2.0 * CC_PI);
    double D = 2.0 * (0.0254 * 3.0);
    for (int i = 0; i < nJ; i++) {
      double J = linspace(0.1, 0.9, nJ, i);
      double V = J * D * n;
      CCOutputs outv[31];
      for (int j = 0; j < nr2; j++) {
        CCOperatingPoint op = cc_simple_op(V, Omega2, sections2[j].r, rho2);
        outv[j] = cc_solve(&rotor2, &sections2[j], &op);
      }
      double T, Q;
      cc_thrusttorque(&rotor2, sections2, outv, nr2, &T, &Q);
      double nd[3];
      cc_nondim(T, Q, V, Omega2, rho2, &rotor2, "propeller", nd);
      CHECK(nd[1], CTTEST[i], 1e-3);
      CHECK(nd[2] * 2.0 * CC_PI, CPTEST[i], 1e-3);
      CHECK(nd[0], ETATEST[i], 1e-3);
    }
    cc_af_free(af);
  }

  /* --- hover regression (Vx = 0 case) --- */
  {
    double Rtip3 = 0.656;
    double Rhub3 = 0.19 * Rtip3;
    CCRotor rotor3 = cc_rotor(Rhub3, Rtip3, 3);

    int nr3 = 30;
    CCSection sections3[30];
    CCAirfoil* base = cc_af_alpha_file("airfoils/naca0012v2.txt", 0);
    if (!base) {
      fprintf(stderr, "failed to load naca0012v2\n");
      n_fail++;
      return;
    }
    CCAirfoil* af2 = cc_af_function(affunc_hover, base);
    for (int i = 0; i < nr3; i++) {
      sections3[i].r =
          linspace(Rhub3 + 0.01 * Rtip3, Rtip3 - 0.01 * Rtip3, nr3, i);
      sections3[i].chord = 0.060;
      sections3[i].theta = 0.0;
      sections3[i].af = af2;
    }

    double rho3 = 1.225;
    double Omega3 = 800.0 * CC_PI / 30.0;
    double Vinf3 = 0.0;

    int nP = 40;
    for (int i = 0; i < nP; i++) {
      double pit = linspace(1e-4, 20.0 * CC_PI / 180.0, nP, i);
      CCOutputs outv[30];
      for (int j = 0; j < nr3; j++) {
        CCOperatingPoint op = cc_simple_op_full(Vinf3, Omega3, sections3[j].r,
                                                rho3, pit, 1.0, 1.0, 0.0);
        outv[j] = cc_solve(&rotor3, &sections3[j], &op);
      }
      double T, Q;
      cc_thrusttorque(&rotor3, sections3, outv, nr3, &T, &Q);
      double nd[3];
      cc_nondim(T, Q, Vinf3, Omega3, rho3, &rotor3, "helicopter", nd);
      CHECK(nd[1], CTCOMP[i], 1e-4);
      CHECK(nd[2], CQCOMP[i], 1e-4);
    }
    cc_af_free(af2);
    cc_af_free(base);
  }
}

/* ============================ correction methods ======================== */

static void test_corrections(void) {
  double cl0 = 0.5, cd0 = 0.001;
  double cl, cd;

  /* Prandtl-Glauert */
  cc_mach_correction_prandtl_glauert(cl0, cd0, 0.6, &cl, &cd);
  if (cl == 0.625 && cd == 0.001)
    n_pass++;
  else {
    n_fail++;
    printf("FAIL: PG correction gave %.17g, %.17g\n", cl, cd);
  }

  /* skin friction */
  double re0 = 1e6;
  cc_re_correction_skin_friction(re0, 0.2, cl0, cd0, 2e6, &cl, &cd);
  if (cl == 0.5)
    n_pass++;
  else {
    n_fail++;
    printf("FAIL: skin friction cl %.17g\n", cl);
  }
  CHECK(cd, 0.000870551, 1e-6);
  cc_re_correction_skin_friction(re0, 0.2, cl0, cd0, 0.5e6, &cl, &cd);
  if (cl == 0.5)
    n_pass++;
  else {
    n_fail++;
    printf("FAIL: skin friction cl %.17g\n", cl);
  }
  CHECK(cd, 0.001148698, 1e-6);

  /* Du-Selig: first test case */
  double D = 5.35;
  double rR = 0.3, cr = 0.37;
  double Omega = 158.0 * CC_PI / 30.0;
  double Vinf = 8.8;
  double tsr = Omega * D / 2.0 / Vinf;

  int na = DS_ALPHAVEC_N;
  double* alphavec = malloc(sizeof(double) * na);
  if (!alphavec) {
    n_fail++;
    printf("FAIL: malloc alphavec\n");
    return;
  }
  for (int i = 0; i < na; i++) alphavec[i] = DS_ALPHAVEC[i] * CC_PI / 180.0;

  double m, alpha0;
  cc_linearliftcoeff(alphavec, DS_CL2D, 3, -2.0 * CC_PI / 180.0,
                     5.0 * CC_PI / 180.0, &m, &alpha0);

  double cdprev;
  cc_re_correction_skin_friction(1e6, 0.2, 0.5, 0.001, 0.5e6, &cl, &cdprev);

  double clo, cdo;
  for (int i = 0; i < na; i++) {
    cc_rotation_correction_duselig_eggers(
        1.0, 1.0, 1.0, m, alpha0, DS_CL2D[i], cdprev, cr, rR, tsr, alphavec[i],
        alphavec[i], 30.0 * CC_PI / 180.0, &clo, &cdo);
    CHECK(clo, DS_CLEXCEL1[i], 5e-5);
  }

  rR = 0.55;
  cr = 0.16;
  for (int i = 0; i < na; i++) {
    cc_rotation_correction_duselig_eggers(
        1.0, 1.0, 1.0, m, alpha0, DS_CL2D[i], cdprev, cr, rR, tsr, alphavec[i],
        alphavec[i], 30.0 * CC_PI / 180.0, &clo, &cdo);
    CHECK(clo, DS_CLEXCEL2[i], 5e-5);
  }
  free(alphavec);

  /* Du-Selig: second test case */
  cr = 0.301;
  rR = 0.3;
  Omega = 72.0 * CC_PI / 30.0;
  Vinf = 10.0;
  D = 10.0;
  tsr = Omega * D / 2.0 / Vinf;

  na = DS2_ALPHAVEC_N;
  alphavec = malloc(sizeof(double) * na);
  if (!alphavec) {
    n_fail++;
    printf("FAIL: malloc alphavec\n");
    return;
  }
  for (int i = 0; i < na; i++) alphavec[i] = DS2_ALPHAVEC[i] * CC_PI / 180.0;

  cc_linearliftcoeff(alphavec, DS2_CL2D, 4, -2.0 * CC_PI / 180.0,
                     5.0 * CC_PI / 180.0, &m, &alpha0);

  for (int i = 0; i < na; i++) {
    cc_rotation_correction_duselig_eggers(
        1.0, 1.0, 1.0, m, alpha0, DS2_CL2D[i], cdprev, cr, rR, tsr, alphavec[i],
        alphavec[i], 30.0 * CC_PI / 180.0, &clo, &cdo);
    CHECK(clo, DS2_CLEXCEL1[i], 5e-5);
  }

  cr = 0.181;
  rR = 0.47;
  for (int i = 0; i < na; i++) {
    cc_rotation_correction_duselig_eggers(
        1.0, 1.0, 1.0, m, alpha0, DS2_CL2D[i], cdprev, cr, rR, tsr, alphavec[i],
        alphavec[i], 30.0 * CC_PI / 180.0, &clo, &cdo);
    CHECK(clo, DS2_CLEXCEL2[i], 5e-5);
  }

  cr = 0.113;
  rR = 0.80;
  for (int i = 0; i < na; i++) {
    cc_rotation_correction_duselig_eggers(
        1.0, 1.0, 1.0, m, alpha0, DS2_CL2D[i], cdprev, cr, rR, tsr, alphavec[i],
        alphavec[i], 30.0 * CC_PI / 180.0, &clo, &cdo);
    CHECK(clo, DS2_CLEXCEL3[i], 5e-5);
  }
  free(alphavec);
}

/* ============================ reference data (Julia) ==================== */

static void test_reference_data(void) {
  /* Akima spline incl. extrapolation points */
  CCAkima* sp = cc_akima(AKIMA_X, AKIMA_Y, AKIMA_X_N);
  if (!sp) {
    n_fail++;
    printf("FAIL: akima construction\n");
    return;
  }
  for (int i = 0; i < AKIMA_NQ; i++)
    CHECK(cc_akima_eval(sp, AKIMA_XQ[i]), AKIMA_YQ[i], 1e-9);
  cc_akima_free(sp);

  /* Viterna on a subset of the NACA64 polar */
  CCAirfoil* naca = cc_af_alpha_file("airfoils/NACA64_A17.dat", 0);
  if (!naca) {
    n_fail++;
    printf("FAIL: load NACA64 for viterna\n");
    return;
  }
  int nsub = 0;
  for (int i = 0; i < naca->nalpha; i++)
    if (naca->alpha[i] >= -20.0 * CC_PI / 180.0 &&
        naca->alpha[i] <= 30.0 * CC_PI / 180.0)
      nsub++;
  double* asub = malloc(sizeof(double) * nsub);
  double* clsub = malloc(sizeof(double) * nsub);
  double* cdsub = malloc(sizeof(double) * nsub);
  if (!asub || !clsub || !cdsub) {
    free(asub);
    free(clsub);
    free(cdsub);
    cc_af_free(naca);
    n_fail++;
    printf("FAIL: malloc sub arrays (reference data)\n");
    return;
  }
  int k = 0;
  for (int i = 0; i < naca->nalpha; i++)
    if (naca->alpha[i] >= -20.0 * CC_PI / 180.0 &&
        naca->alpha[i] <= 30.0 * CC_PI / 180.0) {
      asub[k] = naca->alpha[i];
      clsub[k] = naca->cl[i];
      cdsub[k] = naca->cd[i];
      k++;
    }

  double *av, *clv, *cdv;
  int nv;
  if (cc_viterna(asub, clsub, cdsub, nsub, 0.25, 50, &av, &clv, &cdv, &nv) !=
      0) {
    n_fail++;
    printf("FAIL: viterna\n");
  } else {
    if (nv != VITERNA_ALPHA_N) {
      n_fail++;
      printf("FAIL: viterna length %d != %d\n", nv, VITERNA_ALPHA_N);
    } else {
      for (int i = 0; i < nv; i++) {
        CHECK(av[i], VITERNA_ALPHA[i], 1e-10);
        CHECK(clv[i], VITERNA_CL[i], 1e-10);
        CHECK(cdv[i], VITERNA_CD[i], 1e-10);
      }
    }
    free(av);
    free(clv);
    free(cdv);
  }
  free(asub);
  free(clsub);
  free(cdsub);

  /* write/read round-trip of the AlphaAF (exact, %.17g) */
  if (cc_write_af("naca64_roundtrip.tmp", naca, 1) == 0) {
    CCAirfoil* rt = cc_af_alpha_file("naca64_roundtrip.tmp", 1);
    if (!rt || rt->nalpha != naca->nalpha) {
      n_fail++;
      printf("FAIL: roundtrip reload\n");
    } else {
      int exact = 1;
      for (int i = 0; i < naca->nalpha; i++)
        if (rt->alpha[i] != naca->alpha[i] || rt->cl[i] != naca->cl[i] ||
            rt->cd[i] != naca->cd[i])
          exact = 0;
      if (exact && strcmp(rt->info, naca->info) == 0 &&
          rt->re_info == naca->re_info && rt->mach_info == naca->mach_info)
        n_pass++;
      else {
        n_fail++;
        printf("FAIL: roundtrip data mismatch\n");
      }
    }
    if (rt) cc_af_free(rt);
    remove("naca64_roundtrip.tmp");
  } else {
    n_fail++;
    printf("FAIL: write_af\n");
  }
  cc_af_free(naca);

  /* AlphaReAF */
  CCAirfoil* afre = cc_af_alpha_re(AFRE_ALPHA, AFRE_RE, AFRE_CLM, AFRE_CDM,
                                   AFRE_ALPHA_N, AFRE_RE_N, "ref", 0.0);
  for (int i = 0; i < AFRE_NQ; i++) {
    double cl, cd;
    cc_afeval(afre, AFRE_AQ[i], AFRE_RQ[i], 0.0, &cl, &cd);
    CHECK(cl, AFRE_CLQ[i], 1e-9);
    CHECK(cd, AFRE_CDQ[i], 1e-9);
  }
  cc_af_free(afre);

  /* AlphaMachAF */
  CCAirfoil* afm =
      cc_af_alpha_mach(AFRE_ALPHA, AFMACH_MACH, AFMACH_CLM, AFMACH_CDM,
                       AFRE_ALPHA_N, AFMACH_MACH_N, "ref", 0.0);
  for (int i = 0; i < AFMACH_NQ; i++) {
    double cl, cd;
    cc_afeval(afm, AFRE_AQ[i], 0.0, AFMACH_MQ[i], &cl, &cd);
    CHECK(cl, AFMACH_CLQ[i], 1e-9);
    CHECK(cd, AFMACH_CDQ[i], 1e-9);
  }
  cc_af_free(afm);

  /* AlphaReMachAF */
  CCAirfoil* afrm = cc_af_alpha_re_mach(
      AFRE_ALPHA, AFREMACH_RE, AFREMACH_MACH, AFREMACH_CLM, AFREMACH_CDM,
      AFRE_ALPHA_N, AFREMACH_RE_N, AFREMACH_MACH_N, "ref");
  for (int i = 0; i < AFREMACH_NQ; i++) {
    double cl, cd;
    cc_afeval(afrm, AFRE_AQ[i], AFREMACH_RQ[i], AFREMACH_MQ[i], &cl, &cd);
    CHECK(cl, AFREMACH_CLQ[i], 1e-9);
    CHECK(cd, AFREMACH_CDQ[i], 1e-9);
  }
  cc_af_free(afrm);
}

/* ============================ API coverage ============================= */

static void affunc_nan(double alpha, double Re, double M, void* ud, double* cl,
                       double* cd) {
  (void)alpha;
  (void)Re;
  (void)M;
  (void)ud;
  *cl = NAN;
  *cd = NAN;
}

static void test_api_coverage(void) {
  /* cc_af_simple */
  CCAirfoil* s = cc_af_simple(6.0, 0.05, 1.2, -1.0, 0.01, 0.02);
  double cl, cd;
  cc_afeval(s, 0.15, 0.0, 0.0, &cl, &cd);
  CHECK(cl, 0.6, 1e-12);
  CHECK(cd, 0.0172, 1e-12);
  cc_afeval(s, 1.0, 0.0, 0.0, &cl, &cd);
  CHECK(cl, 1.2, 1e-12); /* capped at clmax */
  CHECK(cd, 0.0388, 1e-12);
  cc_afeval(s, -1.0, 0.0, 0.0, &cl, &cd);
  CHECK(cl, -1.0, 1e-12); /* capped at clmin */
  CHECK(cd, 0.03, 1e-12);
  cc_af_free(s);

  /* cc_akima_deriv vs central finite difference of cc_akima_eval */
  CCAkima* sp = cc_akima(AKIMA_X, AKIMA_Y, AKIMA_X_N);
  if (!sp) {
    n_fail++;
    printf("FAIL: akima construction (deriv)\n");
    return;
  }
  static const double dq[4] = {1.3, 3.7, 6.2, 8.8};
  for (int i = 0; i < 4; i++) {
    double h = 1e-5;
    double fd = (cc_akima_eval(sp, dq[i] + h) - cc_akima_eval(sp, dq[i] - h)) /
                (2.0 * h);
    CHECK(cc_akima_deriv(sp, dq[i]), fd, 1e-6);
  }
  cc_akima_free(sp);

  /* cc_af_alpha from viterna output: Akima passes through nodes exactly */
  double *av, *clv, *cdv;
  int nv;
  int nsub = 0;
  CCAirfoil* naca = cc_af_alpha_file("airfoils/NACA64_A17.dat", 0);
  if (!naca) {
    n_fail++;
    printf("FAIL: load NACA64 (api coverage)\n");
    return;
  }
  for (int i = 0; i < naca->nalpha; i++)
    if (naca->alpha[i] >= -20.0 * CC_PI / 180.0 &&
        naca->alpha[i] <= 30.0 * CC_PI / 180.0)
      nsub++;
  double* asub = malloc(sizeof(double) * nsub);
  double* clsub = malloc(sizeof(double) * nsub);
  double* cdsub = malloc(sizeof(double) * nsub);
  if (!asub || !clsub || !cdsub) {
    free(asub);
    free(clsub);
    free(cdsub);
    cc_af_free(naca);
    n_fail++;
    printf("FAIL: malloc sub arrays\n");
    return;
  }
  int k = 0;
  for (int i = 0; i < naca->nalpha; i++)
    if (naca->alpha[i] >= -20.0 * CC_PI / 180.0 &&
        naca->alpha[i] <= 30.0 * CC_PI / 180.0) {
      asub[k] = naca->alpha[i];
      clsub[k] = naca->cl[i];
      cdsub[k] = naca->cd[i];
      k++;
    }
  if (cc_viterna(asub, clsub, cdsub, nsub, 0.25, 50, &av, &clv, &cdv, &nv) ==
      0) {
    CCAirfoil* vaf = cc_af_alpha(av, clv, cdv, nv, "viterna", 0.0, 0.0);
    if (!vaf) {
      n_fail++;
      printf("FAIL: cc_af_alpha from viterna\n");
    } else {
      for (int i = 0; i < nv; i++) {
        cc_afeval(vaf, av[i], 0.0, 0.0, &cl, &cd);
        CHECK(cl, clv[i], 1e-12);
        CHECK(cd, cdv[i], 1e-12);
      }
      cc_af_free(vaf);
    }
    free(av);
    free(clv);
    free(cdv);
  } else {
    n_fail++;
    printf("FAIL: viterna (api coverage)\n");
  }
  free(asub);
  free(clsub);
  free(cdsub);
  cc_af_free(naca);

  /* files constructors + cc_write_af_multi round-trips */
  {
    static const char* re_files[AFRE_RE_N] = {"rt_re0.tmp", "rt_re1.tmp",
                                              "rt_re2.tmp", "rt_re3.tmp"};
    CCAirfoil* orig = cc_af_alpha_re(AFRE_ALPHA, AFRE_RE, AFRE_CLM, AFRE_CDM,
                                     AFRE_ALPHA_N, AFRE_RE_N, "rt", 0.0);
    if (cc_write_af_multi(re_files, orig, 1) == 0) {
      CCAirfoil* rt = cc_af_alpha_re_files(re_files, AFRE_RE_N, 1);
      if (!rt) {
        n_fail++;
        printf("FAIL: alpha_re_files load\n");
      } else {
        for (int i = 0; i < AFRE_NQ; i++) {
          cc_afeval(rt, AFRE_AQ[i], AFRE_RQ[i], 0.0, &cl, &cd);
          CHECK(cl, AFRE_CLQ[i], 1e-9);
          CHECK(cd, AFRE_CDQ[i], 1e-9);
        }
        cc_af_free(rt);
      }
    } else {
      n_fail++;
      printf("FAIL: write_af_multi re\n");
    }
    cc_af_free(orig);
    for (int i = 0; i < AFRE_RE_N; i++) remove(re_files[i]);
  }
  {
    static const char* m_files[AFMACH_MACH_N] = {"rt_m0.tmp", "rt_m1.tmp",
                                                 "rt_m2.tmp", "rt_m3.tmp"};
    CCAirfoil* orig =
        cc_af_alpha_mach(AFRE_ALPHA, AFMACH_MACH, AFMACH_CLM, AFMACH_CDM,
                         AFRE_ALPHA_N, AFMACH_MACH_N, "rt", 0.0);
    if (cc_write_af_multi(m_files, orig, 1) == 0) {
      CCAirfoil* rt = cc_af_alpha_mach_files(m_files, AFMACH_MACH_N, 1);
      if (!rt) {
        n_fail++;
        printf("FAIL: alpha_mach_files load\n");
      } else {
        for (int i = 0; i < AFMACH_NQ; i++) {
          cc_afeval(rt, AFRE_AQ[i], 0.0, AFMACH_MQ[i], &cl, &cd);
          CHECK(cl, AFMACH_CLQ[i], 1e-9);
          CHECK(cd, AFMACH_CDQ[i], 1e-9);
        }
        cc_af_free(rt);
      }
    } else {
      n_fail++;
      printf("FAIL: write_af_multi mach\n");
    }
    cc_af_free(orig);
    for (int i = 0; i < AFMACH_MACH_N; i++) remove(m_files[i]);
  }
  {
    static const char* rm_files[6] = {"rt_rm0.tmp", "rt_rm1.tmp", "rt_rm2.tmp",
                                      "rt_rm3.tmp", "rt_rm4.tmp", "rt_rm5.tmp"};
    CCAirfoil* orig = cc_af_alpha_re_mach(
        AFRE_ALPHA, AFREMACH_RE, AFREMACH_MACH, AFREMACH_CLM, AFREMACH_CDM,
        AFRE_ALPHA_N, AFREMACH_RE_N, AFREMACH_MACH_N, "rt");
    if (cc_write_af_multi(rm_files, orig, 1) == 0) {
      CCAirfoil* rt = cc_af_alpha_re_mach_files(rm_files, AFREMACH_RE_N,
                                                AFREMACH_MACH_N, 1);
      if (!rt) {
        n_fail++;
        printf("FAIL: alpha_re_mach_files load\n");
      } else {
        for (int i = 0; i < AFREMACH_NQ; i++) {
          cc_afeval(rt, AFRE_AQ[i], AFREMACH_RQ[i], AFREMACH_MQ[i], &cl, &cd);
          CHECK(cl, AFREMACH_CLQ[i], 1e-9);
          CHECK(cd, AFREMACH_CDQ[i], 1e-9);
        }
        cc_af_free(rt);
      }
    } else {
      n_fail++;
      printf("FAIL: write_af_multi re_mach\n");
    }
    cc_af_free(orig);
    for (int i = 0; i < 6; i++) remove(rm_files[i]);
  }

  /* cc_solve_ex success flag: normal case and no-bracket case */
  {
    CCRotor rotor = cc_rotor(1e-6, 100.0, 2);
    CCAirfoil* af2 = cc_af_function(affunc2, NULL);
    CCSection sec = {0.4, 0.1, 0.2, af2};
    CCOperatingPoint op = cc_simple_op(10.0, 200.0, 0.4, 1.225);
    int success = 0;
    CCOutputs o = cc_solve_ex(&rotor, &sec, &op, 10, 0, 0, &success);
    CHECK((double)success, 1.0, 0.0);
    if (o.W > 0.0)
      n_pass++;
    else {
      n_fail++;
      printf("FAIL: solve_ex normal case W=%g\n", o.W);
    }
    cc_af_free(af2);

    CCAirfoil* afnan = cc_af_function(affunc_nan, NULL);
    CCSection secn = {0.4, 0.1, 0.2, afnan};
    printf("(expected warning: no bracket found, NaN polar)\n");
    CCOutputs on = cc_solve_ex(&rotor, &secn, &op, 10, 0, 0, &success);
    CHECK((double)success, 0.0, 0.0);
    CHECK(on.Np, 0.0, 0.0);
    CHECK(on.Tp, 0.0, 0.0);
    cc_af_free(afnan);
  }
}

int main(void) {
  test_normal_operation();
  printf("normal operation: done (cumulative pass=%d fail=%d)\n", n_pass,
         n_fail);
  test_qualitative();
  printf("qualitative check: done (cumulative pass=%d fail=%d)\n", n_pass,
         n_fail);
  test_corrections();
  printf("correction methods: done (cumulative pass=%d fail=%d)\n", n_pass,
         n_fail);
  test_reference_data();
  printf("reference data: done (cumulative pass=%d fail=%d)\n", n_pass, n_fail);
  test_api_coverage();
  printf("api coverage: done (cumulative pass=%d fail=%d)\n", n_pass, n_fail);

  printf("\n%s: %d passed, %d failed\n",
         n_fail == 0 ? "ALL TESTS PASSED" : "FAILURES", n_pass, n_fail);
  return n_fail == 0 ? 0 : 1;
}
